import assert from 'node:assert/strict';
import { clause, peaceClauses, agreedState, approvedState } from './edo1868.fixtures.mjs';
import { activeClauses, agreementVersion, reviewGovernment } from './edo1868-clauses.js';
import { reduceNegotiationEvents, submitGovernmentReview, determineGovernmentOutcome } from './edo1868.js';
import { createEndingRun } from './edo1868-ending.js';
const peace=approvedState();
assert.equal(peace.governmentReview.status,'approved');
assert.equal(determineGovernmentOutcome(peace),'bloodless');
const personal=structuredClone(peaceClauses); personal.at(-1).facts[0].value='personal_guarantee';
assert.equal(reviewGovernment(agreedState(personal)).status,'approved','personal guarantee alone is ratifiable');
const excess=structuredClone(peaceClauses);
excess[0]=clause('徳川家の従来の所領を削らず家名と慶喜の生命身柄を保証する。',{land:'existing_domain',yoshinobu:'protected'},['tokugawa_house','yoshinobu']);
excess[1]=clause('旧臣の禄は全額維持し希望者全員に官職軍職を保証する。費用は新政府が無制限に負担する。',{stipend:'full_retention',employment:'all_applicants',funding:'unbounded_government'},['retainers']);
excess[3].facts.find(f=>f.dimension==='fleet_transfer').value='eventual';
excess.at(-1).facts[0].value='personal_guarantee';
const rejected=submitGovernmentReview({...agreedState(excess),governmentAcceptance:100,promiseCredibility:100,settlementValidity:{government_acceptance:100,promise_credibility:100,internal_consistency:100}});
assert.equal(rejected.governmentReview.status,'changes_requested');
for(const code of ['land_scope','stipend_capacity','appointment_capacity','fiscal_limit','combined_obligations','fleet_control'])assert.ok(rejected.governmentReview.findings.some(f=>f.code===code),code);
assert.equal(determineGovernmentOutcome(rejected),'empty_promises');
const original=agreementVersion(peace.canonicalLedger);
assert.equal(reviewGovernment({...peace,governmentAcceptance:0,promiseCredibility:0}).status,'approved');
assert.equal(agreementVersion({...peace.canonicalLedger,events:[]}),original);
const id=peace.canonicalLedger.proposals[0].id;
const packageResult=reduceNegotiationEvents({...peace,turns:5},[{type:'agreement_confirmed',actor:'katsu',issue_ids:['edo_castle'],terms:'全てを書面に',reference_proposal_ids:[id],clauses:[],commitment:'firm'}],{playerText:'全て書面にしてください。',katsuText:'先の条件全てを書面に記す。'});
assert.equal(packageResult.validationError,undefined);
assert.equal(agreementVersion(packageResult.state.canonicalLedger),original);
assert.equal(activeClauses(packageResult.state.canonicalLedger).length,6);
const changed=peace.canonicalLedger.proposals[0].clauses[1].id;
const newClause=clause('旧臣への支援を新政府の予算内で三ヶ月に変更し、登用は選抜する。',{stipend:'bounded_support',employment:'selection',funding:'bounded_government'},['retainers']);
const modification=reduceNegotiationEvents({...peace,turns:6},[{type:'proposal_modified',actor:'saigo',target_proposal_id:id,changed_clause_ids:[changed],issue_ids:['retainers'],terms:newClause.text,clauses:[newClause]}],{playerText:newClause.text,katsuText:'期間変更は検討したい。'});
assert.equal(modification.validationError,undefined);
assert.equal(activeClauses(modification.state.canonicalLedger).length,5);
assert.equal(activeClauses(modification.state.canonicalLedger,{acceptedOnly:false}).length,6);
assert.ok(activeClauses(modification.state.canonicalLedger).every(c=>c.id!==changed));
assert.notEqual(agreementVersion(modification.state.canonicalLedger),original);
const malformed=structuredClone(newClause);malformed.source_quote='言っていない原文';
const invalid=reduceNegotiationEvents(peace,[{type:'proposal_created',actor:'saigo',issue_ids:['retainers'],terms:malformed.text,clauses:[malformed]}],{playerText:newClause.text,katsuText:'検討する。'});
assert.ok(invalid.validationError);assert.equal(agreementVersion(invalid.state.canonicalLedger),original);
const unknown=structuredClone(peaceClauses);unknown[3].facts=[];
assert.ok(reviewGovernment(agreedState(unknown)).findings.some(f=>f.code==='fleet_control'));
const run=createEndingRun({endingId:'bloodless',state:peace,messages:[],discoveries:[]});
assert.equal(run.settlementSnapshot.acceptedTerms.length,6);
assert.ok(run.settlementSnapshot.acceptedTerms.some(c=>c.terms.includes('指揮・保管')));
console.log('Structured obligation, independent ratification, package retention, amendment and evidence tests passed');

import { compileUpdates, materializeClauseEvidence, updateSchema } from './edo1868-clauses.js';
// Confirmation has no replacement payload: exact original clauses survive.
const confirmation = {target:id, agreement_status:'mutual', commitment:'firm', changed_clause_ids:[], issue_ids:['edo_castle'], terms:'既存の詳細条件に改めて同意', clauses:[]};
const confirmed = reduceNegotiationEvents({...peace,turns:7}, compileUpdates([confirmation]), {playerText:'先の詳細のまま書面に。',katsuText:'先の条件に同意する。市民を傷つけることは認めない。'});
assert.equal(confirmed.validationError,undefined,'unrelated negative language cannot veto an explicit structured confirmation');
assert.equal(agreementVersion(confirmed.state.canonicalLedger),original);
assert.throws(()=>compileUpdates([{...confirmation,target:'new'}]),/detailed clauses/);
const badAmendment=reduceNegotiationEvents(peace,compileUpdates([{...confirmation,changed_clause_ids:[changed]}]),{playerText:'変更する。',katsuText:'同意する。'});
assert.ok(badAmendment.validationError,'an empty replacement never deletes an obligation');
assert.equal(agreementVersion(badAmendment.state.canonicalLedger),original);
assert.ok(updateSchema(peace.canonicalLedger.proposals).anyOf,'transport constrains changes to nonempty replacement clauses');
const raw={text:'半年だけ全額支援',issue_ids:['retainers'],source_ref:'current_player_message',subject:'旧臣',obligor:'新政府',scope:'全額',duration:'半年',funding:'bounded_government',approval_authority:'submit_for_approval',dependency_clause_ids:[],facts:[{kind:'stipend:full_retention',phase:'unspecified',source_ref:'current_player_message'}]};
const evidence=materializeClauseEvidence([{clauses:[raw]}],'半年だけ全額支援する。','その期間で同意する。')[0].clauses[0];
assert.equal(evidence.source_quote,'半年だけ全額支援する。');
assert.equal(evidence.facts[0].quote,evidence.source_quote);
assert.equal(evidence.facts[0].dimension,'stipend');
// A backed, bounded full payment/appointment promise is not rejected by a keyword.
const financed=structuredClone(peaceClauses);
financed[1]=clause('半年間の禄を全額、既定予算の上限内で支払う。対象者全員に対応する職枠を確保する。',{stipend:'full_retention',funding:'bounded_government',support_duration:'bounded',cost_scope:'capped',employment:'all_applicants',appointment_capacity:'bounded_positions'},['retainers']);
assert.equal(reviewGovernment(agreedState(financed)).status,'approved');
const phases=structuredClone(peaceClauses);
phases[3].facts.forEach(f=>f.phase='interim');
phases[3].facts.push({dimension:'fleet_command',value:'government',phase:'final',quote:phases[3].text});
assert.equal(reviewGovernment(agreedState(phases)).status,'approved','future government command does not contradict interim Katsu command');
phases[3].facts=phases[3].facts.filter(f=>f.dimension!=='fleet_command'||f.phase==='final');
assert.ok(reviewGovernment(agreedState(phases)).findings.some(f=>f.code==='fleet_control'),'future command alone cannot establish interim command');
const stale=createEndingRun({endingId:'bloodless',state:{...modification.state,governmentReview:peace.governmentReview},messages:[],discoveries:[]});
assert.equal(stale.settlementSnapshot.governmentAccepted,false,'old approval cannot authorize a changed agreement');
assert.ok(Object.isFrozen(peace.governmentReview.snapshot.clauses));
console.log('Transport, bounded guarantees, temporal fleet control and stale approval tests passed');
const splitRetainers=structuredClone(peaceClauses);
splitRetainers.push(clause('旧臣の登用は能力で選抜する。',{employment:'selection'},['retainers']));
const splitState=agreedState(splitRetainers);
const splitTarget=splitState.canonicalLedger.proposals[0];
const reopened=reduceNegotiationEvents({...splitState,turns:8},[{type:'proposal_modified',actor:'saigo',target_proposal_id:splitTarget.id,changed_clause_ids:[splitTarget.clauses[1].id],issue_ids:['retainers'],terms:newClause.text,clauses:[newClause]}],{playerText:newClause.text,katsuText:'支援期間の変更は持ち帰って考えたい。'});
assert.equal(reopened.validationError,undefined);
assert.equal(reopened.state.issues.retainers,'proposed','a separate unchanged hiring clause cannot conceal the pending support amendment');
assert.equal(reopened.state.issues.warships,'agreed');
assert.ok(activeClauses(reopened.state.canonicalLedger).some(c=>c.text==='旧臣の登用は能力で選抜する。'));
console.log('Selective reopening with another accepted clause on the same issue passed');
import { overpromiseClauses } from './edo1868.fixtures.mjs';
let ten=agreedState(overpromiseClauses);
const tenVersion=agreementVersion(ten.canonicalLedger);
for(let turn=5;turn<20;turn++){
 const out=reduceNegotiationEvents({...ten,turns:turn},[{type:'agreement_confirmed',actor:'katsu',issue_ids:['peaceful_transition'],terms:'先の詳細条件を変えず書面に記す。',reference_proposal_ids:[ten.canonicalLedger.proposals[0].id],clauses:[],commitment:'firm'}],{playerText:'先の条件のまま書面に。',katsuText:'これまでの約束を変えず書面に記す。'});
 assert.equal(out.validationError,undefined);ten=out.state;
}
assert.equal(agreementVersion(ten.canonicalLedger),tenVersion);
assert.deepEqual(activeClauses(ten.canonicalLedger).map(c=>c.text),overpromiseClauses.map(c=>c.text));
assert.equal(reviewGovernment(ten).status,'changes_requested');
assert.equal(reviewGovernment(ten).snapshot.clauses.length,10);
console.log('Ten overpromises survive repeated package confirmations and independent review');
const mixedAuthority=structuredClone(peaceClauses);
mixedAuthority[0].approval_authority='personal_guarantee';
mixedAuthority[1].funding='domain_revenue';
assert.equal(reviewGovernment(agreedState(mixedAuthority)).status,'approved','distinct obligations can use distinct approval routes and compatible funding sources');
assert.ok(createEndingRun({endingId:'empty_promises',state:rejected,messages:[],discoveries:[]}).endingNarrative.includes('新政府が求めた修正'));
console.log('Per-obligation finance/authority and concrete refusal narrative passed');
const linkedSupport=structuredClone(peaceClauses);
linkedSupport[1]=clause('旧臣の禄は別条項の財源と期間、上限を条件に全額維持する。',{stipend:'full_retention'},['retainers']);
linkedSupport.push(clause('支援財源は新政府の予算内とし、半年の期限と支出上限を設ける。',{funding:'bounded_government',support_duration:'bounded',cost_scope:'capped'},['retainers']));
const linkedState=agreedState(linkedSupport);
const linkedProposal=linkedState.canonicalLedger.proposals[0];
linkedProposal.clauses[1].dependencies=[linkedProposal.clauses.at(-1).id];
assert.equal(reviewGovernment(linkedState).status,'approved','explicit dependencies can provide fiscal backing from another clause');
linkedProposal.clauses[1].dependencies=['missing-clause'];
assert.ok(reviewGovernment(linkedState).findings.some(f=>f.code==='unmet_dependency'));
assert.ok(reviewGovernment(linkedState).findings.some(f=>f.code==='stipend_capacity'));
console.log('Explicit clause dependencies provide evidence without borrowing unrelated resources');
const fleetPatch=clause('軍艦の保管責任は双方で負う。',{fleet_custody:'joint'},['warships']);
const fleetBefore=peace.canonicalLedger.proposals[0].clauses[3];
const fleetPatched=reduceNegotiationEvents({...peace,turns:9},[{type:'proposal_modified',actor:'saigo',target_proposal_id:id,changed_clause_ids:[fleetBefore.id],issue_ids:['warships'],terms:fleetPatch.text,clauses:[fleetPatch],response:'accept',commitment:'firm'}],{playerText:fleetPatch.text,katsuText:'保管責任だけをそのように変更する。'});
assert.equal(fleetPatched.validationError,undefined);
const fleetAfter=activeClauses(fleetPatched.state.canonicalLedger).find(c=>c.supersedes?.includes(fleetBefore.id));
assert.equal(fleetAfter.facts.find(f=>f.dimension==='fleet_custody').value,'joint');
for(const dimension of ['fleet_command','fleet_oversight','fleet_use','fleet_transfer'])assert.deepEqual(fleetAfter.facts.find(f=>f.dimension===dimension),fleetBefore.facts.find(f=>f.dimension===dimension));
assert.equal(reviewGovernment(fleetPatched.state).status,'approved');
assert.ok(fleetAfter.inheritedTerms.some(t=>t.text.includes('一覧確認後')));
const rescinded=clause('軍艦の移管手順の合意を取り消し、未定とする。',{fleet_transfer:'unknown'},['warships']);
const rescind=reduceNegotiationEvents({...fleetPatched.state,turns:10},[{type:'proposal_modified',actor:'saigo',target_proposal_id:fleetAfter.proposalId,changed_clause_ids:[fleetAfter.id],issue_ids:['warships'],terms:rescinded.text,clauses:[rescinded],response:'accept',commitment:'firm'}],{playerText:rescinded.text,katsuText:'移管手順を未定に戻す。'});
assert.equal(rescind.validationError,undefined);
assert.ok(reviewGovernment(rescind.state).findings.some(f=>f.code==='fleet_control'),'explicit withdrawal does not inherit an old transfer promise');
console.log('Amendments preserve unnamed dimensions and explicit withdrawals replace them');
const phasedState=structuredClone(peace);
const phasedProposal=phasedState.canonicalLedger.proposals[0];
const phasedFleet=phasedProposal.clauses[3];
phasedFleet.facts.find(f=>f.dimension==='fleet_command').phase='interim';
phasedFleet.facts.push({dimension:'fleet_command',value:'government',phase:'final',quote:phasedFleet.text});
const commandPatch=clause('移管までは共同指揮に変更する。',{fleet_command:'joint'},['warships']);commandPatch.facts[0].phase='interim';
const phasedChange=reduceNegotiationEvents({...phasedState,turns:11},[{type:'proposal_modified',actor:'saigo',target_proposal_id:phasedProposal.id,changed_clause_ids:[phasedFleet.id],issue_ids:['warships'],terms:commandPatch.text,clauses:[commandPatch],response:'accept',commitment:'firm'}],{playerText:commandPatch.text,katsuText:'移管までの指揮だけ共同にする。'});
assert.equal(phasedChange.validationError,undefined);
const phasedActive=activeClauses(phasedChange.state.canonicalLedger).find(c=>c.supersedes?.includes(phasedFleet.id));
assert.ok(phasedActive.facts.some(f=>f.dimension==='fleet_command'&&f.phase==='final'&&f.value==='government'));
assert.ok(phasedActive.facts.some(f=>f.dimension==='fleet_command'&&f.phase==='interim'&&f.value==='joint'));
assert.equal(reviewGovernment(phasedChange.state).status,'approved');
console.log('Interim command amendments preserve separately agreed final command');
const withdrawnClause=reduceNegotiationEvents({...peace,turns:12},[{type:'proposal_withdrawn',actor:'saigo',target_proposal_id:id,changed_clause_ids:[fleetBefore.id],issue_ids:['warships'],terms:'軍艦の条項だけを撤回する。'}],{playerText:'軍艦の条項だけを撤回する。',katsuText:'他の約束は変えない。'});
assert.equal(withdrawnClause.validationError,undefined);
assert.equal(activeClauses(withdrawnClause.state.canonicalLedger).length,5);
assert.equal(withdrawnClause.state.issues.yoshinobu,'agreed');
assert.equal(withdrawnClause.state.issues.warships,'unresolved');
console.log('Clause withdrawal preserves the rest of a signed package');
const inheritedRun=createEndingRun({endingId:'bloodless',state:submitGovernmentReview(fleetPatched.state),messages:[],discoveries:[]});
assert.ok(inheritedRun.endingNarrative.includes('変更しない軍艦の指揮'));
assert.ok(inheritedRun.endingNarrative.includes('一覧確認後に新政府へ順次移管'));
assert.ok(!inheritedRun.endingNarrative.includes('fleet_command'));
console.log('Inherited promise details remain readable without internal dimension names');
const combined=structuredClone(peaceClauses);
combined[3]=clause('武器を封印し、軍艦は勝が保管して一覧確認後に引き渡す。',{weapons:'joint_seal',fleet_custody:'katsu',fleet_transfer:'scheduled'},['weapons','warships']);
const combinedState=agreedState(combined);
const combinedProposal=combinedState.canonicalLedger.proposals[0];
const combinedAmend=reduceNegotiationEvents({...combinedState,turns:13},[{type:'proposal_modified',actor:'saigo',target_proposal_id:combinedProposal.id,changed_clause_ids:[combinedProposal.clauses[3].id],issue_ids:['warships'],terms:fleetPatch.text,clauses:[fleetPatch],response:'accept',commitment:'firm'}],{playerText:fleetPatch.text,katsuText:'保管だけを変更する。'});
assert.equal(combinedAmend.validationError,undefined);
assert.equal(combinedAmend.state.issues.weapons,'agreed');
assert.ok(activeClauses(combinedAmend.state.canonicalLedger).some(c=>c.supersedes?.length&&c.issueIds.includes('weapons')&&c.facts.some(f=>f.dimension==='weapons')));
console.log('Legacy mixed clauses retain the issue links of unchanged obligations');
const civic=clause('勝から新政府へ治安を引き継ぎ、市民の命を保護する。',{order:'transition',civilians:'protected'},['public_order']);
const civicResult=reduceNegotiationEvents({...peace,turns:14},[{type:'agreement_confirmed',actor:'katsu',issue_ids:['public_order'],terms:civic.text,clauses:[civic],commitment:'firm'}],{playerText:civic.text,katsuText:'この引継ぎと市民保護に同意する。'});
assert.equal(civicResult.validationError,undefined);
const civicProposal=civicResult.state.canonicalLedger.proposals.at(-1);
assert.ok(civicProposal.issueIds.includes('civilian_safety'));
assert.ok(civicProposal.issueIds.includes('peaceful_transition'));
assert.ok(!civicProposal.issueIds.includes('edo_castle'),'derived links do not invent a castle surrender');
console.log('Typed obligations derive consistent issue links without prose keyword decisions');

// A generic obligation amendment must not retain the superseded promise merely
// because the extractor attaches the fleet-oriented final/unspecified phase.
const jobsBefore = agreedState(overpromiseClauses);
const jobsProposal = jobsBefore.canonicalLedger.proposals[0];
const oldJobs = jobsProposal.clauses.find(c=>c.facts.some(f=>f.dimension==='employment'&&f.value==='all_applicants'));
const jobsPatch = clause('全員任用を改め、配置できる職枠と能力に応じて登用する。',{employment:'selection'},['retainers']);
jobsPatch.facts[0].phase='final';
const jobsChange=reduceNegotiationEvents({...jobsBefore,turns:15},[{type:'proposal_modified',actor:'saigo',target_proposal_id:jobsProposal.id,changed_clause_ids:[oldJobs.id],issue_ids:['retainers'],terms:jobsPatch.text,clauses:[jobsPatch],response:'accept',commitment:'firm'}],{playerText:jobsPatch.text,katsuText:'全員への保証を改め、その登用条件を受け入れる。'});
assert.equal(jobsChange.validationError,undefined);
const revisedJobs=activeClauses(jobsChange.state.canonicalLedger).find(c=>c.supersedes?.includes(oldJobs.id));
assert.deepEqual(revisedJobs.facts.filter(f=>f.dimension==='employment').map(f=>f.value),['selection']);
assert.ok(!reviewGovernment(jobsChange.state).findings.some(f=>f.code==='conflicting_employment'));
console.log('Employment amendments replace old guarantees regardless of fleet phase labels');

const groupedBefore=agreedState([
 clause('旧臣の従来の禄を全額維持する。',{stipend:'full_retention'},['retainers']),
 clause('旧臣の希望者全員に職を用意する。',{employment:'all_applicants'},['retainers']),
]);
const groupedProposal=groupedBefore.canonicalLedger.proposals[0];
const groupedText='禄は半年の予算内支援へ変更し、職は能力と職枠に応じた登用に改める。';
const groupedClauses=[clause(groupedText,{stipend:'bounded_support'},['retainers']),clause(groupedText,{employment:'selection'},['retainers'])];
const groupedChange=reduceNegotiationEvents({...groupedBefore,turns:16},[{type:'proposal_modified',actor:'saigo',target_proposal_id:groupedProposal.id,changed_clause_ids:groupedProposal.clauses.map(c=>c.id),issue_ids:['retainers'],terms:groupedText,clauses:groupedClauses,response:'accept',commitment:'firm'}],{playerText:groupedText,katsuText:'禄と登用の変更に同意する。'});
assert.equal(groupedChange.validationError,undefined);
const groupedActive=activeClauses(groupedChange.state.canonicalLedger);
assert.deepEqual(groupedActive[0].facts.map(f=>f.dimension+':'+f.value),['stipend:bounded_support']);
assert.deepEqual(groupedActive[1].facts.map(f=>f.dimension+':'+f.value),['employment:selection']);
console.log('Grouped amendments do not mix pay and hiring obligations on the same issue');

const splitOld=agreedState([clause('旧臣の禄を全額維持し、希望者全員に官職を用意する。',{stipend:'full_retention',employment:'all_applicants'},['retainers'])]);
const splitOldProposal=splitOld.canonicalLedger.proposals[0];
const splitChange=reduceNegotiationEvents({...splitOld,turns:17},[{type:'proposal_modified',actor:'saigo',target_proposal_id:splitOldProposal.id,changed_clause_ids:[splitOldProposal.clauses[0].id],issue_ids:['retainers'],terms:groupedText,clauses:groupedClauses,response:'accept',commitment:'firm'}],{playerText:groupedText,katsuText:'それぞれの変更を受け入れる。'});
assert.equal(splitChange.validationError,undefined);
assert.deepEqual(activeClauses(splitChange.state.canonicalLedger).flatMap(c=>c.facts.map(f=>f.dimension+':'+f.value)),['stipend:bounded_support','employment:selection']);
assert.throws(()=>compileUpdates([{target:splitOldProposal.id,agreement_status:'mutual',changed_clause_ids:['one','two'],clauses:groupedClauses}]),/one original clause/);
console.log('Splitting one revised clause cannot resurrect sibling superseded facts');
